name: Documentación

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'

      - name: Instalar dependencias
        run: |
          julia --project=docs -e '
            using Pkg;
            Pkg.develop(Pkg.PackageSpec(path=pwd()));
            Pkg.instantiate()'

      - name: Construir y publicar documentación
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs docs/make.jl
